### ISSUE TITLE
LUA error when mousevering some interactive items in the world

### ISSUE THREAD

**Issue by Heregellas** [enolgor/wow-addon-tiptac#2] opened 2020-10-17 23:13 UTC
Hey, I had this LUA error when interacting with the Vindicaar console. First time I got it since the fix from this noon, I copy it here if you can have an idea ?

Message: Interface\AddOns\TipTac\ttStyle.lua:247: attempt to index local 'gttLine' (a nil value)
Time: Sun Oct 18 01:06:48 2020
Count: 4
Stack: Interface\AddOns\TipTac\ttStyle.lua:247: attempt to index local 'gttLine' (a nil value)
[string "@Interface\AddOns\TipTac\ttStyle.lua"]:247: in function `ModifyUnitTooltip'
[string "@Interface\AddOns\TipTac\ttStyle.lua"]:287: in function `?'
[string "@Interface\AddOns\TipTac\ttCore.lua"]:297: in function `SendElementEvent'
[string "@Interface\AddOns\TipTac\ttCore.lua"]:656: in function `ApplyUnitAppearance'
[string "@Interface\AddOns\TipTac\ttCore.lua"]:818: in function <Interface\AddOns\TipTac\ttCore.lua:779>
[string "=[C]"]: ?

Locals: self = <table> {
 GenerateTargetLines = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:80
 OnLoad = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:256
 GenerateNpcLines = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:180
 GeneratePetLines = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:149
 GeneratePlayerLines = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:101
 name = "Style"
 ModifyUnitTooltip = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:204
 OnCleared = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:290
 OnStyleTip = <function> defined @Interface\AddOns\TipTac\ttStyle.lua:260
}
u = <table> {
 isPlayer = false
 reactionIndex = 5
 isPetWild = false
 class = "Navigation Console"
 classID = "WARRIOR"
 powerType = 1
 token = "mouseover"
 name = "Navigation Console"
 reactionColor = ""
 title = "<<<+50  Unknown>>>"
 isPetCompanion = false
}
first = true
unit = "mouseover"
level = 50
classification = "elite"
gttLine = nil
(*temporary) = "GameTooltipTextLeft3"
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "count"
(*temporary) = "count"
(*temporary) = "attempt to index local 'gttLine' (a nil value)"
UnitName = <function> defined =[C]:-1
cfg = <table> {
 classification_rare = "%s (Rare) "
 classification_elite = "+%s "
 left = 24.999968
 if_enable = true
 optionsLeft = 760.000122
 anchorFrameTipType = "normal"
 classification_trivial = "~%s "
 classification_worldboss = "%s (Boss) "
 if_showItemLevelAndId = false
 anchorFrameUnitPoint = "BOTTOMLEFT"
 anchorWorldTipPoint = "BOTTOMRIGHT"
 anchorFrameTipPoint = "BOTTOMLEFT"
 classification_normal = "%s "
 classification_rareelite = "+%s (Rare) "
 anchorWorldUnitType = "mouse"
 showGuildRank = true
 targetYouText = "<<YOU>>"
 hideUFTipsInCombat = false
 top = 267.426758
 optionsBottom = 370.000244
 hideAllTipsInCombat = false
 if_showAuraCaster = false
 classification_minus = "-%s "
 anchorWorldTipType = "mouse"
 anchorFrameUnitType = "normal"
 anchorWorldUnitPoint = "BOTTOMRIGHT"
}
lineInfo = <table> {
 1 = ""
 2 = "+50 "
 3 = " "
 4 = ""
 5 = "Unknown"
 6 = ""
 7 = "+50 "
 8 = " "
 9 = ""
 10 = "Unknown"
 11 = ""
 12 = "+50 "
 13 = " "
 14 = ""
 15 = "Unknown"
 16 = ""
 17 = "+50 "
 18 = " "
 19 = ""
 20 = "Unknown"
 21 = ""
 22 = "+50 "
 23 = " "
 24 = ""
 25 = "Unknown"
 26 = ""
 27 = "+50 "
 28 = " "
 29 = ""
 30 = "Unknown"
 31 = ""
 32 = "+50 "
 33 = " "
 34 = ""
 35 = "Unknown"
 36 = ""
 37 = "+50 "
 38 = " "
 39 = ""
 40 = "Unknown"
 41 = ""
 42 = "+50 "
 43 = " "
 44 = ""
 45 = "Unknown"
 46 = ""
 47 = "+50 "
 48 = " "
 49 = ""
 50 = "Unknown"
 count = 50
 Index = 3
}
tt = TipTac {
 CreatePushArray = <function> defined @Interface\AddOns\TipTac\ttCore.lua:268
 elements = <table> {
 }
 ClassColorMarkup = <table> {
 }
 AddModifiedTip = <function> defined @Interface\AddOns\TipTac\ttCore.lua:945
 MirrorAnchorsSmart = <table> {
 }
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:443
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 CVAR_UPDATE = <function> defined @Interface\AddOns\TipTac\ttCore.lua:394
 u = <table> {
 }
 ApplyBackdrop = <function> defined @Interface\AddOns\TipTac\ttCore.lua:518
 SetBackdrop = <func

Thank you in advance ! :)

**Comment by enolgor** [comment] 2020-10-18 12:39
I'm not able to reproduce the error. Can you give me another example or can you try again in the Vindicaar navigation console and see if it's a recurring error?

**Comment by Heregellas** [comment] 2020-10-18 14:16
Oddly enough I can't reproduce it neither with the Vindicaar console, it happened twice (with two different character's connections), but nothing today with my testings so far :/
Will reach you again if I have other instances of that type of bug/error, maybe it's related to another add-on, making some conflict ?
Thank you anyway for your quick answer !

**Comment by enolgor** [comment] 2020-10-18 14:19
I will close it for the moment but let's keep an eye on the error and reopen it if we can reproduce it.

**Closed as completed by enolgor** 2020-10-18 14:19 UTC
